[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mpt"
version = "0.7.1"
description = "Mobile Pentest Toolkit (MPT)"
authors = [
    {name = "Alexander Subbotin", email = "dev@bytesnipers.com"},
]
readme = "README.md"
keywords = ["MPT", "mobile"]
classifiers = [
    "Programming Language :: Python :: 3",
    'Operating System :: OS Independent'
]
dependencies = [
    "GitPython",
    "colorlog",
    "colorama",
    "tabulate",
    "frida-tools",
]

[project.urls]
Homepage = "https://github.com/ByteSnipers/mobile-pentest-toolkit"
Repository = "https://github.com/ByteSnipers/mobile-pentest-toolkit"
Changelog = "https://github.com/ByteSnipers/mobile-pentest-toolkit/blob/master/CHANGELOG.md"

[project.scripts]
mpt = "mpt.console:cli"